blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
# post views
path('', views.post_list, name='post_list'),
path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
path('feed/', LatestPostsFeed(), name='post_feed'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

jtalks/urls.py
from django.urls import path
from . import views

app_name = 'jtalks'

urlpatterns = [
    path('', views.home, name='jtalks-home'),
    path('about/', views.about, name='jtalks-about'),
    path('get_courses/', views.GetCourses.as_view(), name='get_courses'),
    path('load-more-data/', views.load_more_data, name='load_more_data'),
    path('load_more_products/', views.load_more_products, name='load_more_products'),
    path('search_more_products/', views.search_more_products, name='search_more_products'),
    path('search_products/', views.search_products, name='search_products')
]

jtalks_institute/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from courses.views import CourseListView
from users.views import user_signup
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jtalks.urls', namespace='jtalks')),
    path('forum/', include('forum.urls', namespace='forum')),
    # path("categories/", CourseListView.as_view(), name='category'),
    # path("course/", CourseListView.as_view(), name='courses'),
    # path("c/", include("courses.urls", namespace="courses")),
    path('signup/', user_signup, name='signup'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('course/', include('courses.urls', namespace='courses')),
    path('product/', include('products.urls', namespace='product')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views, ajax_view

app_name = 'product'

urlpatterns = [
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('create_order/', views.order_create, name='order_create'),
    path('ajax_payment/', views.ajax_payment, name='ajax_payment'),
    path('pay_with_paystack/', ajax_view.AjaxPayment.as_view(), name='pay_with_paystack'),
    path('<int:id>/pdf', views.Pdf.as_view(), name='render_pdf'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "jtalks/base.html" %}
{% load static %}

{% block title %}Your shopping cart{% endblock %}
{% block blog_style %}
    <link rel="stylesheet" href="{%static 'css/products.css'%}" />
{% endblock blog_style %}
{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url}}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                    </a>
                </td>

                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.override }}
                        <input type="submit" value="Update">
                        {% csrf_token %}
                    </form>
                </td>

                <td>
                    <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                        <input type="submit" value="Remove">
                        {% csrf_token %}
                    </form>
                </td>

                <td class="num">N{{ item.price }}</td>
                <td class="num">N{{ item.total_price }}</td>
            </tr>
            {% endwith %}
            {% endfor %}

            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">N{{ cart.get_total_price }}</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'jtalks:jtalks-home' %}" class="button light">Continue shopping</a>
        <a href="{% url 'product:order_create' %}" class="button">Checkout</a>
    </p>
{% endblock %}