blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
# post views
path('', views.post_list, name='post_list'),
path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
path('feed/', LatestPostsFeed(), name='post_feed'),
]

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'

urlpatterns = [
    path('new/', views.post_create, name='post_new'),
    path('', views.post_list, name='post_list'),
    path('<int:id>/<str:slug>/', views.post_detail, name='post_detail'),
    path('<int:id>/<str:slug>/edit/', views.post_edit, name='post_edit'),
    path('<int:id>/<str:slug>/delete/', views.post_delete, name='post_delete'),
    path('add_category/', views.add_category, name='add_category'),
    path("<category>/", views.blog_category, name="blog_category"),
    path('like/<int:id>/<str:slug>/', views.like_view, name='like_post'),
]

jtalks_institute/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from courses.views import CourseListView
from users.views import user_signup
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jtalks.urls', namespace='jtalks')),
    path('forum/', include('forum.urls', namespace='forum')),
    # path("categories/", CourseListView.as_view(), name='category'),
    # path("course/", CourseListView.as_view(), name='courses'),
    # path("c/", include("courses.urls", namespace="courses")),
    path('signup/', user_signup, name='signup'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('course/', include('courses.urls', namespace='courses')),
    path('product/', include('products.urls', namespace='product')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('user_profile/<int:id>/', views.user_profile, name='user_profile'),
]

forum/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone

# Create your models here.

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=10000)

    def __str__(self):
        return self.name


class Post(models.Model):
    categories = models.ManyToManyField(Category, related_name='posts')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=250, unique_for_date='date', null=True, blank=True)
    title = models.CharField(max_length=255)
    body = models.TextField()
    image = models.ImageField(upload_to='blog images/', null=True)
    likes = models.ManyToManyField(User, related_name='blog_post', null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title} by {self.author.username} ({self.categories.name})'

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('forum:post_detail', args=[str(self.id)])

    @property
    def number_of_comments(self):
        return Comment.objects.filter(post=self).count()


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    comment = models.TextField()
    date = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('forum:post_list')

forum/forms.py
from django import forms
from .models import Category, Comment


# add category

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', )
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Add a category name...'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(
                attrs={'class': 'contact_text', 'placeholder': 'Write your comment here ...', 'required': 'true'})
        }

forum/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import Post, Category, Comment
from .forms import CategoryForm, CommentForm


def post_list(request):
    all_posts = Post.objects.all().order_by('-date')
    paginator = Paginator(all_posts, 5)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    categories = Category.objects.all()

    if request.method == 'POST':
        query = request.POST.get('q', None)
        submit_button = request.POST.get('submit')

        if query is not None:
            lookups = Q(title__icontains=query) | Q(body__icontains=query)
            results = Post.objects.filter(lookups).distinct()
            context = {
                'query': query,
                'results': results,
                'submit_button': submit_button
            }
            return render(request, 'forum/search_results.html', context)
    context = {
        'posts': posts,
        'categories': categories,
        'title': all_posts[0].title if all_posts else None,
        'id': all_posts[0].id if all_posts else None,
        'slug': all_posts[0].slug if all_posts else None,
    }
    return render(request, 'forum/post_list.html', context)


def post_detail(request, id, slug):
    post = get_object_or_404(Post, id=id, slug=slug)
    comments = post.comments.filter(active=True).order_by('-updated')
    new_comment = None
    liked = False
    if post.likes.filter(id=request.user.id).exists:
        liked = True
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.author = request.user
            new_comment.save()
    else:
        comment_form = CommentForm()

    context = {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'liked': liked
    }
    return render(request, 'forum/post_detail.html', context)


@login_required
def post_create(request):
    categories = Category.objects.all()

    if request.method == 'POST':
        user_category = request.POST['category']
        title = request.POST['title']
        body = request.POST['body']
        image = request.FILES['photo']

        t_str = title.lower()
        for i in range(0, len(t_str), 1):
            if t_str[i] == ' ':
                t_str = t_str.replace(t_str[i], '-')

        category = Category.objects.get(name=user_category)

        new_post = Post.objects.create(author=request.user, slug=t_str, title=title, body=body, image=image)
        new_post.save()
        new_post.categories.add(category)
        return redirect('/forum/')

    context = {
        'categories': categories
    }
    return render(request, 'forum/post_new.html', context)


@login_required
def post_edit(request, id, slug):
    post = get_object_or_404(Post, id=id, slug=slug)

    if request.method == 'POST':
        title = request.POST['title']
        body = request.POST['body']

        post.title = title
        post.body = body
        post.save()
        return redirect('/forum/')

    context = {
        'post': post
    }
    return render(request, 'forum/post_edit.html', context)


@login_required
def post_delete(request, id, slug):
    post = get_object_or_404(Post, id=id, slug=slug)
    if request.method == 'POST':
        ask = request.POST['ask']
        if ask == 'Yes':
            post.delete()
            return redirect('/forum/')
        elif ask == 'No':
            return redirect('/forum/')
    return render(request, 'forum/post_delete.html', {'post': post})


def like_view(request, id, slug):
    post = get_object_or_404(Post, id=request.POST.get('post_id'), slug=slug)
    post.likes.add(request.user)
    return HttpResponseRedirect(reverse('forum:post_detail', args=[int(id), str(slug)]))


def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            categories = Category.objects.all()
            context = {
                'categories': categories
            }
            return render(request, 'forum/post_new.html', context)

    else:
        form = CategoryForm()
    return render(request, 'forum/category.html', {'form': form})


def blog_category(request, category):
    posts = Post.objects.filter(
        categories__name__contains=category
    ).order_by(
        '-date'
    )
    context = {
        "category": category,
        "posts": posts
    }
    return render(request, "forum/category_post_list.html", context)

forum/templates/forum/category_post_list.html
{% extends 'jtalks/base.html' %}
{% load static %}
{% block title %}Jtalk Blog | Blog Categories{% endblock title %}
{% block blog_new %}Add Post{% endblock blog_new %}

{% block blog_style %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/forum.css' %}" />
{% endblock blog_style %}


{% block content %}
<div class="blog">
    <div class="container">
        <div class="row">

            <div class="col-lg-9">
                <div class="blog_content">
                    <h2>{{ posts.count }} post{{ posts.count|pluralize }} in category: {{ category }}</h2>
                    <!-- Add Blog Details -->
                    {% if posts %}
                    {% for post in posts %}
                    <div class="blog_post">
                        <div class="blog_image">
                            <img src="{{ post.author.photo.url }}">
                        </div>
                        <div class="blog_title">
                            <a href="{% url 'forum:post_detail' post.pk post.slug %}">{{ post.title }}</a>
                        </div>
                        <div class="blog_meta">
                            <ul>
                                <li>By <a href="{% url 'users:user_profile' post.author.id %}">{{ post.author }}</a></li>
                                {% for category in post.categories.all %}
                                <li>In {{ category.name }}</li>
                                {% endfor %}
                                {% if post.number_of_comments %}
                                    {% with post.number_of_comments as total_comments %}
                                        <li><a href="{% url 'forum:post_detail' post.pk post.slug %}">{{ total_comments }} Comment{{ total_comments|pluralize }}</a></li>
                                    {% endwith %}
                                {% else %}
                                    <li>0 Comment</li>
                                {% endif %}
                                <li> On {{ post.date }}</li>
                            </ul>
                        </div>
                        <div class="blog_text">
                            <p>{{ post.body | slice:":150" }}...</p>
                        </div>
                        <div class="blog_buttons" style="display:flex; flex-direction: row; justify-content: space-between; align-items: center;">
                            <div class="blog_link"><a href="{% url 'forum:post_detail' post.pk post.slug %}">Read More</a></div>
                            <div class="blog_link"><a href="{% url 'forum:post_new' %}">New Post</a></div>
                            {% if request.user == post.author %}
                                <div class="blog_link"><a href="{% url 'forum:post_edit' post.pk post.slug %}">Edit</a></div>
                                <div class="blog_link"><a href="{% url 'forum:post_delete' post.pk post.slug %}">Delete</a></div>
                            {% endif %}
                            </div>
                        <hr>
                        </div>
                    {% endfor %}
                    {% else %}
                        <h2>No blog post is available. Be the first to share a post</h2>
                    {% endif %}
                    <!-- End Blog Details -->


                </div>

                <div class="blog_pages">
                    <ul>
                        <span class="step-links">
                            {% if posts.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a></li>
                            {% endif %}
                            <span class="current">
                                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                            </span>
                            {% if posts.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">Next</a></li>
                            {% endif %}
                        </span>
                    </ul>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock content %}

forum/templates/forum/post_delete.html
{% extends 'jtalks/base.html' %}
{% load static %}
{% block title %}Jtalk Blog | Delete Post{% endblock title %}
{% block content %}
<section class="vh-105">
  <div class="container py-5 h-110">
    <div class="row justify-content-center align-items-center h-110">
      <div class="col-12 col-lg-9 col-xl-7">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px">
          <div class="card-body p-4 p-md-5">
            <h1 class="mb-4 pb-2 pb-md-0 mb-md-5">Are you sure you want to delete this post - "{{ post.title }}" ?</h1>
            <form method="POST">
              {% csrf_token %}
              <div class="row">
                <div class="col-12">
                  <select class="contact_input" name="ask">
                    <option value="Yes">Yes</option>
                    <option value="No">No</option>
                  </select>
                  <!-- <label class="form-label select-label">Choose option</label> -->
                </div>
              </div>
              
              <div class="mt-4 pt-2">
                <input class="btn btn-secondary btn-lg" type="submit" value="Delete Post" />
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block js %}
<script>
    function showPassword() {
    var x = document.getElementById('password');
    if (x.type === 'password') {
        x.type = 'text';
    } else {
        x.type = 'password'
    }
};

function showPassword2() {
    var x = document.getElementById('password2');
    if (x.type === 'password') {
        x.type = 'text';
    } else {
        x.type = 'password'
    }
}
</script>
{% endblock js %}

forum/templates/forum/post_detail.html
{% extends 'jtalks/base.html' %}
{% load static %}
{% block title %}Jtalk Blog | Post Details{% endblock title %}
{% block blog_new %}Add Post{% endblock blog_new %}

{% block blog_style %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/forum.css' %}" />
{% endblock blog_style %}


{% block content %}
<div class="blog">
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <div class="blog_content">
                    <!-- Add Blog Details -->
                    <div class="blog_post">
                      <hr>
                        <div class="blog_image">
                            <img src="{{ post.author.photo.url }}">
                        </div>
                        <div class="blog_title">
                            {{ post.title }}
                        </div>
                        <div class="blog_meta">
                            <ul>
                                <li>By <a href="{% url 'users:user_profile' post.author.id %}">{{ post.author }}</a></li>
                                {% for category in post.categories.all %}
                                <li>In
                                    <a href="{% url 'forum:blog_category' category.name %}">
                                        {{ category.name }}
                                    </a></li>
                                {% endfor %}
                                {% if comments %}
                                    {% with comments.count as total_comments %}
                                        <li>{{ total_comments }} Comment{{ total_comments|pluralize }}</li>
                                    {% endwith %}
                                {% else %}
                                    <li>0 Comment</li>
                                {% endif %}
                                <li> On {{ post.date }}</li>
                                <li>{{ post.total_likes }} Like{{ post.total_likes|pluralize }}</li>
                            </ul>
                        </div>
                        <div class="blog_text">
                            <p>{{ post.body}}</p>
                        </div>
                        <div class="blog_buttons" style="display:flex; flex-direction: row; justify-content: space-between; align-items: center;">
                            <div class="blog_link"><a href="{% url 'forum:post_new' %}">New Post</a></div>
                            <div class="blog_link"><a href="{% url 'forum:post_list' %}">All Posts</a></div>
                            {% if request.user == post.author %}
                                <div class="blog_link"><a href="{% url 'forum:post_edit' post.pk post.slug %}">Edit</a></div>
                                <div class="blog_link"><a href="{% url 'forum:post_delete' post.pk post.slug %}">Delete</a></div>
                            {% endif %}
                        </div>

                        <div>
                          
                          {% if user.is_authenticated %}
                            <form action="{% url 'forum:like_post' post.id post.slug %}" method="POST">
                              {% csrf_token %}
                              <button class="like_post" type="submit" name="post_id" value="{{ post.id }}">Like Post</button>
                              <strong>- {{ post.total_likes }} Like{{ post.total_likes|pluralize }}</strong>
                            </form>
                          {% else %}
                            <form action="{% url 'forum:like_post' post.id post.slug %}" method="POST" class="request_login">
                              {% csrf_token %}
                              <small><a href="{% url 'users:login' %}?next={{request.path}}" style="color: purple;">Please Login to like this post</a></small>
                            </form>
                          {% endif %}
                        </div>
                    </div>
                </div>
                <!-- End Blog Details -->
            </div>

            <div class="col-lg-5">
                <span>
                    <img src="#" alt="" style="max-width: 100%";>
                </span>
            </div>

            <!-- Start Comment Section -->
            <div class="col-lg-6">
                <!-- Display Comment Section -->
                {% if comments %}
                    <!-- <strong class="text-secondary">{{ object.number_of_comments }} Comment{{ object.number_of_comments|pluralize }}</strong> -->
                    {% with comments.count as total_comments %}
                        <strong>{{ total_comments }} comment{{ total_comments|pluralize }}</strong>
                    {% endwith %}
                    <hr>
                    <ul>
                        {% for comment in comments %}
                            <li>
                                <div class="blog_meta">
                                    <ul>
                                        <li>Comment {{ forloop.revcounter }} By <a href="{% url 'users:user_profile' comment.author.id %}">{{ comment.author }}</a></li>
                                        <li> On {{ comment.date }}</li>
                                    </ul>
                                </div>
                                <div class="blog_text">
                                    {% if comment.author.gender == 'Male' %}
                                    <p> He wrote:<br>{{ comment.comment|safe }}</p>
                                    {% else %}
                                    <p> She wrote:<br>{{ comment.comment|safe }}</p>
                                    {% endif %}
                                </div>
                            </li>
                            <hr>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong class="text-secondary">No comments yet...</strong>
                {% endif %}
                <!-- End Display Comment Section -->
            </div>

            <div class="col-lg-6">
                <!--Add Comment Form -->
                <div class="blog_title">
                    <h2>Leave your comment:</h2>
                </div>
                <div id="contact_form_section">
                    {% if user.is_authenticated %}
                        {% if new_comment %}
                            <h2>Your comment has been added successfully.</h2>
                            <h2>Add another comment</h2>
                            <form class="contact_form" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    {{ comment_form.as_p }}
                                </div>
                                <button class="like_post">Add comment</button>
                            </form>
                        {% else %}
                            <h2>Add a new comment</h2>
                            <form class="contact_form" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    {{ comment_form.as_p }}
                                </div>
                                <button class="like_post">Add comment</button>
                            </form>
                        {% endif %}
                    {% else %}
                        <button class="like_post">
                            <a href="{% url 'users:login' %}?next={{request.path}}" style="color: purple;">Please Log in to add a comment!</a>
                        </button>
                    {% endif %}
                </div>
                <!--End Comment Form -->
            </div>
            <!-- End Comment Section -->


        </div>
    </div>
</div>
{% endblock content %}

forum/templates/forum/post_list.html
{% extends 'jtalks/base.html' %}
{% load static %}
{% block title %}Jtalk Blog | Home{% endblock title %}
{% block blog_new %}Add Post{% endblock blog_new %}

{% block blog_style %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/forum.css' %}" />
{% endblock blog_style %}


{% block content %}
<div class="blog">
    <div class="container">
        <div class="row">

            <div class="col-lg-9">
                <div class="blog_content">
                  <hr>
                    <!-- Add Blog Details -->
                    {% if posts %}
                    {% for post in posts %}
                    <div class="blog_post">
                        <div class="blog_image">
                            <img src="{{ post.author.photo.url }}">
                        </div>
                        <div class="blog_title">
                            <a href="{% url 'forum:post_detail' post.pk post.slug %}">{{ post.title }}</a>
                        </div>
                        <div class="blog_meta">
                            <ul>
                                <li>By <a href="{% url 'users:user_profile' post.author.id %}">{{ post.author }}</a></li>
                                {% for category in post.categories.all %}
                                <li>In
                                    <a href="{% url 'forum:blog_category' category.name %}">
                                        {{ category.name }}
                                    </a></li>
                                {% endfor %}
                                {% if post.number_of_comments %}
                                    {% with post.number_of_comments as total_comments %}
                                        <li><a href="{% url 'forum:post_detail' post.pk post.slug %}">{{ total_comments }} Comment{{ total_comments|pluralize }}</a></li>
                                    {% endwith %}
                                {% else %}
                                    <li>0 Comment</li>
                                {% endif %}
                                <li> On {{ post.date }}</li>
                                <li>{{ post.total_likes }} Like{{ post.total_likes|pluralize }}</li>
                            </ul>
                        </div>
                        <div class="blog_text">
                            <p>{{ post.body | slice:":150" }}...</p>
                        </div>
                        <div class="blog_buttons" style="display:flex; flex-direction: row; justify-content: space-between; align-items: center;">
                            <div class="blog_link"><a href="{% url 'forum:post_detail' post.pk post.slug %}">Read More</a></div>
                            <div class="blog_link"><a href="{% url 'forum:post_new' %}">New Post</a></div>
                            {% if request.user == post.author %}
                                <div class="blog_link"><a href="{% url 'forum:post_edit' post.pk post.slug %}">Edit</a></div>
                                <div class="blog_link"><a href="{% url 'forum:post_delete' post.pk post.slug %}">Delete</a></div>
                            {% endif %}
                            </div>
                        <hr>
                        </div>
                    {% endfor %}
                    {% else %}
                        <h2>No blog post is available. Be the first to share a post</h2>
                    {% endif %}
                    <!-- End Blog Details -->


                </div>

                <div class="blog_pages">
                    <ul>
                        <span class="step-links">
                            {% if posts.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a></li>
                            {% endif %}
                            <span class="current">
                                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                            </span>
                            {% if posts.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">Next</a></li>
                            {% endif %}
                        </span>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 sidebar_col">
                <div class="blog_sidebar">

                    <div class="sidebar_section">
                        <div class="sidebar_search">
                            <form method="POST">
                                {% csrf_token %}
                                <input class="sidebar_search_input" type="search" placeholder="Search Posts" name="q" required>
                                <input type="submit" name="submit" value="Search" class="input_button">
                                <!--
                                <button type="submit" name="submit" class="sidebar_search_button d-flex flex-column align-items-center justify-content-center">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                                -->
                            </form>
                        </div>
                    </div>

                    <div class="sidebar_section">
                        <div class="sidebar_title">Latest Post</div>
                        <div class="latest_news_container">

                            <div class="latest_news d-flex flex-row align-items-start justify-content-start">
                                <div class="latest_news_content">
                                    <div class="latest_news_title"><a href="/forum/{{ id }}/{{ slug }}">{{ title }}</a>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="sidebar_section">
                        <div class="sidebar_title">Categories</div>
                        <div class="sidebar_list">
                            <ul>
                                {% for category in categories %}
                                <li>
                                    <a class="d-flex flex-row align-items-start justify-content-start" href="{% url 'forum:blog_category' category.name %}">
                                        {{ category }}<span class="ml-auto"></span></a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}