blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
# post views
path('', views.post_list, name='post_list'),
path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
path('feed/', LatestPostsFeed(), name='post_feed'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

jtalks/urls.py
from django.urls import path
from . import views

app_name = 'jtalks'

urlpatterns = [
    path('', views.home, name='jtalks-home'),
    path('about/', views.about, name='jtalks-about'),
    path('get_courses/', views.GetCourses.as_view(), name='get_courses'),
    path('load-more-data/', views.load_more_data, name='load_more_data'),
    path('load_more_products/', views.load_more_products, name='load_more_products'),
    path('search_more_products/', views.search_more_products, name='search_more_products'),
    path('search_products/', views.search_products, name='search_products')
]

jtalks_institute/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from courses.views import CourseListView
from users.views import user_signup
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jtalks.urls', namespace='jtalks')),
    path('forum/', include('forum.urls', namespace='forum')),
    # path("categories/", CourseListView.as_view(), name='category'),
    # path("course/", CourseListView.as_view(), name='courses'),
    # path("c/", include("courses.urls", namespace="courses")),
    path('signup/', user_signup, name='signup'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('course/', include('courses.urls', namespace='courses')),
    path('product/', include('products.urls', namespace='product')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views, ajax_view

app_name = 'product'

urlpatterns = [
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('create_order/', views.order_create, name='order_create'),
    path('ajax_payment/', views.ajax_payment, name='ajax_payment'),
    path('pay_with_paystack/', ajax_view.AjaxPayment.as_view(), name='pay_with_paystack'),
    path('<int:id>/pdf', views.Pdf.as_view(), name='render_pdf'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('user_profile/<int:id>/', views.user_profile, name='user_profile'),
]

products/models.py
import random
import string
from django.db import models
from django.urls import reverse


def random_code(digit=7, letter=3):
    sample_str = ''.join((random.choice(string.digits) for i in range(digit)))
    sample_str += ''.join((random.choice(string.ascii_uppercase) for i in range(letter)))

    sample_list = list(sample_str)
    final_string = ''.join(sample_list)
    return final_string


class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:product_detail', args=[self.id, self.slug])


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    reference_id = models.CharField(max_length=200, null=True, blank=True)
    order_id = models.CharField(default=random_code, max_length=10, null=True, blank=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

products/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'phone_number', 'city']

products/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.views import View
from cart.cart import Cart
from cart.forms import CartAddProductForm
from .forms import OrderCreateForm
from .models import Product, OrderItem, Order
from .render import Render


def product_detail(request, id, slug):
    cart = Cart(request)
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    return render(request, 'products/details.html', {
        'product': product,
        'cart_product_form': cart_product_form,
        'cart': cart
    })


# create orders
def order_create(request):
    cart = Cart(request)

    if request.method == 'POST':
        form = OrderCreateForm(request.POST)

        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
            # clear the cart
            # cart.clear()
            # launch asynchronous task
            # order_created.delay(order.id)
            context = {
                'order': order,
                'cart': cart,
                'email': form.cleaned_data['email'],
                'phone': form.cleaned_data['phone_number']
            }
            return render(request, 'products/pay_with_paystack.html', context)
    else:
        form = OrderCreateForm()
        return render(request, 'products/create_order.html', {'cart': cart, 'form': form})


def ajax_payment(request):
    # order_req = get_object_or_404(Order, order_id)
    if request.is_ajax():
        reference_id = request.POST.get('reference')
        x = Order(reference=reference_id, paid=True)
        x.save()
        if x:
            response = {
                'message': "Your Payment was successfully received"
            }
            return JsonResponse(response)
        else:
            response = {
                'message': "Your Payment Failed"
            }
            return JsonResponse(response)


# view for pdf rendering
class Pdf(View):

    def get(self, request, id):
        cart = Cart(request)
        order_item = get_object_or_404(Order, id=id)
        today = timezone.now()
        # clear the cart
        cart.clear()
        params = {
            'id': id,
            'today': today,
            'cart': cart,
            'order_item': order_item,
            # 'request': request
        }
        return Render.render('products/pdf.html', params)

products/templates/products/create_order.html
{% extends "jtalks/base.html" %}
{% block title %}
    Checkout
{% endblock %}

{% block content %}
    <h1>Checkout</h1>
    <div class="order-info">
        <h3>Your order</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>&#8358;{{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p>Total: &#8358;{{ cart.get_total_price }}</p>
    </div>

    <form method="post" class="order-form">
        <p>Pay total sum of &#8358;{{ cart.get_total_price }}</p><br>
        {{ form.as_p }}
        <p><input type="submit" value="Place order"></p>
        {% csrf_token %}
    </form>
{% endblock %}

products/templates/products/created.html
{% extends "jtalks/base.html" %}
{% block title %}
    Thank you
{% endblock %}

{% block content %}
    <h1>Thank you</h1>
    <p>Your order has been successfully completed. Your order number is<strong>{{ order.id }}</strong>.</p>
{% endblock %}

products/templates/products/details.html
{% extends 'jtalks/base.html' %}
{%load static%}

{%block content %}

<section id="about-home">
  <h2>Enroll Our Popular Courses And Skill Up</h2>
</section>

<section id="course-inner">
  <div class="overview">
    <div style="width: 100%;">
      <img class="course-img" src="{% if course.cover %}{{ course.cover.url }}{% else %}https://dummyimage{% endif %}" alt="{{ course.name }}" style="max-width: 50%;"/>
    </div>
    <div class="course-head">
      <div class="c-name">
        <h2>{{course.name}}</h2>
        <div class="scores">
          <div class="star">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
          </div>
          <div class="review">
            <h6>Reviews - 4.5/5 <i class="far fa-star text-warning"></i></h6>
          </div>
          {% if request.user.is_authenticated %}
            {% if can_add %}
              <div>
                <button type="button" class="btn btn-warning btn-sm float-right hide_btn" data-bs-toggle="modal" data-bs-target="#courseReview">Add Review</button>
              </div>
            {% endif %}
          {% else %}
          <h6>Please login to add your review</h6>
          {% endif %}
          <!-- Course Review Starts-->
          <!-- Button trigger modal -->
          <!-- Modal -->
          {% if request.user.is_authenticated %}
          <div class="modal fade" id="courseReview" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Review This Course</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                
                <div class="modal-body">
                  <form id="addForm" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="course_id" value="{{ course.id }}">
                    <table class="table table-bordered">
                      {{ form.as_table }}
                    </table>
                    <p class="ajaxRes"></p>
                    <div class="modal-footer">
                  <input id="review_submit" type="submit" class="btn btn-primary" value="Add Review">
                </div>
                  </form>
                </div>
                
              </div>
            </div>
          </div>
          {% endif %}
          <!-- Course Review Ends-->
        </div>
        <!-- <p>{{course.description|linebreaks }}</p> -->
      </div>
      <span>&#8358;{{course.price}}</span>
      <div>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input id="btn_1" type="submit" value="Add to cart">
        </form>
      </div>
    </div>
    <h3>Instructor</h3>
    <div class="tutor">
      <div >
        <img src="{% if course.tutor_image %}{{ course.tutor_image.url }}{% else %}https://dummyimage{% endif %}" alt=""/>
      </div>
      <div class="tutor-det">
        <h5>{{course.tutor}}</h5>
        <p>{{course.tutor_title}}</p>
      </div>
    </div>
    <hr />
    <h3>Course Overview</h3>
    <p>{{course.overview|linebreaks }}</p>
    <hr />
    <h3>What you'll learn</h3>
    <div class="learn">
      <p>
        <i class="far fa-check-circle"></i>JavaScript from scratch - beginner to
        advanced
      </p>
      <p>
        <i class="far fa-check-circle"></i>Everything you need to become a
        JavaScript expert and apply for JavaScript jobs
      </p>
      <p>
        <i class="far fa-check-circle"></i>All about variables, functions,
        objects and arrays
      </p>
      <p>
        <i class="far fa-check-circle"></i>All core features and concepts you
        need to know in modern JavaScript development
      </p>
      <p>
        <i class="far fa-check-circle"></i>Project-driven learning with plenty
        of examples
      </p>
      <p><i class="far fa-check-circle"></i>Object-oriented programming</p>
    </div>
  </div>
  
  <div>
    <div class="enroll">
      <h3>This course includes:</h3>
      <p><i class="far fa-video"></i>52 hours video</p>
      <p><i class="far fa-newspaper"></i>75 articles</p>
      <p><i class="far fa-cloud-download"></i>Downloadable resources</p>
      <p><i class="far fa-infinity"></i>Full lifetime access</p>
      <p><i class="fas fa-mobile-alt"></i>Access on mobile and TV</p>
      <p><i class="far fa-paperclip"></i>Assignments</p>
      <p><i class="far fa-trophy-alt"></i>Certificate of completion</p>
      {% if request.user.is_authenticated %}
        <div class="enroll-btn">
          <a id="enroll_btn" class="blue" href="#" data-course-id="{{ course.id }}" data-user="{{ request.user }}">
            Enroll Course
            <i class="fas fa-angle-double-right load-more-icon"></i>
          </a>
        </div>
      {% else %}
        <div class="enroll-btn">
          <a class="blue" href="{% url 'users:login' %}?next={{request.path}}">Login To Enroll For this Course</a>
        </div>
      {% endif %}
  </div>
    <h3>User Reviews - {{ total_data }}</h3>
  <div class="review-list">
    {% for review in all_reviews %}
    <div class="card review-box" style="margin-bottom: 15px; box-shadow: 0px 20px 40px 0px rgb(11 2 55 / 8%); border-radius: 11px; height: auto; padding-left: 5px;">
      <div class="star-date" style="display: flex; flex-direction: row; justify-content: space-between;">
        <div class="star">
        {% if review.review_rating == '1' %}
        <i class="fas fa-star star_color"></i>
        <i class="far fa-star"></i>
        <i class="far fa-star"></i>
        <i class="far fa-star"></i>
        <i class="far fa-star"></i>
        {% elif review.review_rating == '2' %}
        <i class="fas fa-star star_color"></i>
        <i class="fas fa-star star_color"></i>
        <i class="far fa-star"></i>
        <i class="far fa-star"></i>
        <i class="far fa-star"></i>
        {% elif review.review_rating == '3' %}
        <i class="fas fa-star star_color"></i>
        <i class="fas fa-star star_color"></i>
        <i class="fas fa-star star_color"></i>
        <i class="far fa-star"></i>
        <i class="far fa-star"></i>
        {% elif review.review_rating == '4' %}
        <i class="fas fa-star star_color"></i>
        <i class="fas fa-star star_color"></i>
        <i class="fas fa-star star_color"></i>
        <i class="fas fa-star star_color"></i>
        <i class="far fa-star"></i>
        {% elif review.review_rating == '5' %}
        <i class="fas fa-star star_color"></i>
        <i class="fas fa-star star_color"></i>
        <i class="fas fa-star star_color"></i>
        <i class="fas fa-star star_color"></i>
        <i class="fas fa-star star_color"></i>
        {% endif %}
      </div>
        
        <div class="dated">
          <small style="float: right;">{{ review.rated }}</small>
        </div>
      </div>
      <p style="width:300px; word-wrap: break-word;">{{ review.review_text }}</p>
      <small>by {{ review.user.first_name }} {{ review.user.last_name }}</small>
    </div>
    {% endfor %}
  </div>
    <div>
      <button class="enroll-btn" id="load_more_review" data-total="{{ total_data }}" data-limit="3" data-course-id="{{ course.id }}">
        <a class="blue">
          Load More
          <i class="fas fa-angle-double-right load-more-icon"></i>
        </a>
      </button>
      <p class="review_end" style="display: none;">No more reviews...</p>
    </div>
  </div>
</section>
{%endblock content%}
{% block js %}
<script src="{% static 'jtalks/home.js' %}"></script>
{% endblock js %}

products/templates/products/pay_with_paystack.html
{% extends "jtalks/base.html" %}
{% load static %}

{% block title %}Payment With Paystack{% endblock %}

{% block content %}
    <div class='container' onload="payWithPaystack()">
        <div class='row justify-content-md-center'>
            <div class='col-md-auto'>
                <div id="output">

                </div>

                <div id="success">

                </div>

                <div id="display_info" style="display: none">
                    <p>Click <a href="{% url 'product:render_pdf' order.id %}" target="_blank">Here</a> to print receipt of your purchase</p>
                    <p id="home">Go Back To Shop <a href="{% url 'jtalks:jtalks-home' %}">Homepage</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script>
        window.onload=function(){
            $("#display_info").hide();
            payWithPaystack();
        };

        function payWithPaystack(){
            var a = '{{ cart.get_total_price }}';
            var handler = PaystackPop.setup({
                key: 'pk_test_ce8979497f703eb955ab5ceb19fc54cdcb615e0d',
                email:'{{email}}',
                amount: parseInt(a) * 100,
                currency: "NGN",
                metadata: {
                    custom_fields: [
                        {
                            display_name: "Mobile Number",
                            variable_name: "mobile_number",
                            value: "{{phone}}",
                            order_id: "{{ order.id }}"
                        }
                    ]
                },

                callback: function(response){
                    var ref = response.reference;
                    var order_random_id = '{{ order.order_id }}'
                    var order_id = '{{ order.id }}'
                    //console.log(order_id)
                    
                    // $('div#home').show();
                    $.ajax({
                        method: "GET",
                        url: "{% url 'product:pay_with_paystack' %}",
                        data: {
                            'id': order_id,
                          'reference': ref,
                        },
                        dataType: "json",

                        success: function (data) {
                            if (data.message == "Your Payment was successfully received") {
                                $('#output').html(data.message)
                                $('#success').html(`<p>Transaction reference is : <h2>${ref}</h2> and your order id is <h2>${order_random_id}</h2></p>`);
                                $("#display_info").show();
                            } else if (data.message == "Your Payment Failed!!!") {
                                $('#output').html(data.message)
                                $("#success").html(`<a href="{% url 'product:order_create' %}" class="button">Checkout</a>`)
                            }
                        },
                    });
                },

                onClose: function(){
                    alert('window closed');
                }
            });

            handler.openIframe();
        }
    </script>
{% endblock js %}

products/templates/products/pdf.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    
    <title>Order Summary</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }

        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }

        .table tbody + tbody {
            border-top: 2px solid #000;
        }

        .table .table {
            background-color: #fff;
        }

        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }

        .header {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }

    </style>
</head>
<body>

<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="header">
                <h1>ADS Online Shopping Center</h1>
                <h3>Address: 58, Onibuore Area, Off Monatan - Iyana Church Road, Monatan Ibadan, Nigeria.</h3>
                <small>Contact: 08187669362, 09032055129</small>
                <small>Email: akinade.mayowa@gmail.com</small>
            </div>

            <h3 style="float: right;">Date - {{ today | date:"d/m/Y" }}</h3>
        </div>

        <div class="list-group">
            <h3>Order Summary:</h3>
            <div class="row">
                <div class="col-6">
                    <p>Name: {{ order_item.first_name }} {{ order_item.last_name }}</p>
                    <p>Paid: {{ order_item.paid }}</p>
                    <p>Reference ID: {{ order_item.reference_id }}</p>
                    <p>Order ID: {{ order_item.order_id }}</p>
                </div>
                <div class="col-6">
                    <p>Email: {{ order_item.email }}</p>
                    <p>Address: {{ order_item.address }}</p>
                    <p>Phone Number: {{ order_item.phone_number }}</p>
                    <p>City: {{ order_item.city }}</p>
                </div>
            </div>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Product</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ item.product.name }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>N{{ item.total_price }}</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="3">TOTAL</td>
                    <td>{{ cart.get_total_price}}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"></script>
</body>
</html>