blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
# post views
path('', views.post_list, name='post_list'),
path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
path('feed/', LatestPostsFeed(), name='post_feed'),
]

courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    path('', views.course_list, name='course_list'),
    path('<int:id>/<slug:slug>/', views.course_detail, name='course_detail'),
    path('save_review/', views.SaveReview.as_view(), name='save_review'),
    path('load_more_review/', views.load_more_review, name='load_more_review'),
    path('create_user_library/', views.UserCourse.as_view(), name='user_library'),
    path('<str:username>/user_library/', views.user_library, name='user_library'),
    path('pay_for_courses/', views.AjaxCoursePayment.as_view(), name='pay_for_courses'),
    path('<int:id>/print_course_pdf', views.CoursePdf.as_view(), name='print_course_pdf'),
    path('search_more_courses/', views.search_more_courses, name='search_more_courses'),
    path('search_courses/', views.search_courses, name='search_courses')
]

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'

urlpatterns = [
    path('new/', views.post_create, name='post_new'),
    path('', views.post_list, name='post_list'),
    path('<int:id>/<str:slug>/', views.post_detail, name='post_detail'),
    path('<int:id>/<str:slug>/edit/', views.post_edit, name='post_edit'),
    path('<int:id>/<str:slug>/delete/', views.post_delete, name='post_delete'),
    path('add_category/', views.add_category, name='add_category'),
    path("<category>/", views.blog_category, name="blog_category"),
    path('like/<int:id>/<str:slug>/', views.like_view, name='like_post'),
]

jtalks/urls.py
from django.urls import path
from . import views

app_name = 'jtalks'

urlpatterns = [
    path('', views.home, name='jtalks-home'),
    path('about/', views.about, name='jtalks-about'),
    path('get_courses/', views.GetCourses.as_view(), name='get_courses'),
    path('load-more-data/', views.load_more_data, name='load_more_data'),
    path('load_more_products/', views.load_more_products, name='load_more_products'),
    path('search_more_products/', views.search_more_products, name='search_more_products'),
    path('search_products/', views.search_products, name='search_products')
]

jtalks_institute/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from courses.views import CourseListView
from users.views import user_signup
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jtalks.urls', namespace='jtalks')),
    path('forum/', include('forum.urls', namespace='forum')),
    # path("categories/", CourseListView.as_view(), name='category'),
    # path("course/", CourseListView.as_view(), name='courses'),
    # path("c/", include("courses.urls", namespace="courses")),
    path('signup/', user_signup, name='signup'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('course/', include('courses.urls', namespace='courses')),
    path('product/', include('products.urls', namespace='product')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views, ajax_view

app_name = 'product'

urlpatterns = [
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('create_order/', views.order_create, name='order_create'),
    path('ajax_payment/', views.ajax_payment, name='ajax_payment'),
    path('pay_with_paystack/', ajax_view.AjaxPayment.as_view(), name='pay_with_paystack'),
    path('<int:id>/pdf', views.Pdf.as_view(), name='render_pdf'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('user_profile/<int:id>/', views.user_profile, name='user_profile'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
        self).get_queryset().filter(status='published')

class Post(models.Model):

    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    STATUS_CHOICES = [
        ('draft', 'Draft'),
        ('published', 'Published')
    ]
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(to = get_user_model(), on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    image = models.ImageField(upload_to='blog images/', null=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.

    class Meta:
        ordering = ('-publish', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                self.publish.month,
                                                self.publish.day, 
                                                self.slug])

# Comments on blog post
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment

# class EmailPostForm(forms.Form):
#     name = forms.CharField(max_length=25)
#     email = forms.EmailField()
#     to = forms.EmailField()
#     comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Comment, Post
from .forms import CommentForm

# Create your views here.
def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
    # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
    # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, 
                                status='published', 
                                publish__year=year, 
                                publish__month=month, 
                                publish__day=day)
    return render(request, 'blog/post/detail.html', {'post': post})

# forms for post
# def post_share(request, post_id):
#     # Retrieve post by id
#     post = get_object_or_404(Post, id=post_id, status='published')

#     if request.method == 'POST':
#         # Form was submitted
#         form = EmailPostForm(request.POST)
#     if form.is_valid():
#         # Form fields passed validation
#         cd = form.cleaned_data
#         # ... send email
#     else:
#         form = EmailPostForm()
#     return render(request, 'blog/post/share.html', {'post': post, 'form': form})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, 
                                    status='published', 
                                    publish__year=year, 
                                    publish__month=month, 
                                    publish__day=day)
# List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
        # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
        # Assign the current post to the comment
            new_comment.post = post
        # Save the comment to the database
            new_comment.save()

    else:
        comment_form = CommentForm()
    return render(request,'blog/post/detail.html',  
                                {'post': post, 
                                'comments': comments,
                                'new_comment': new_comment, 
                                'comment_form': comment_form})

jtalks/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views import View
from courses.models import Category, Courses
from cart.cart import Cart
from cart.forms import CartAddProductForm
from products.models import Product


def home(request):
    cart = Cart(request)
    categories = Category.objects.all()
    courses = Courses.objects.all().order_by('-id')[:2]
    for course in courses:
        print(course.is_featured)
    total_data = Courses.objects.count()

    # for products
    products = Product.objects.all().order_by('-id')[:2]
    total_products = Product.objects.count()

    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    context = {
        'categories': categories,
        'courses': courses,
        'total_data': total_data,
        'products': products,
        'total_products': total_products,
        'cart': cart
    }
    return render(request, 'jtalks/home.html', context)


def load_more_data(request):
    offset = int(request.GET['offset'])
    limit = int(request.GET['limit'])
    data = Courses.objects.order_by('-id')[offset:offset+limit]
    t = render_to_string('jtalks/more_courses.html', {'data': data})
    return JsonResponse({'data': t})


def load_more_products(request):
    offset = int(request.GET['offset'])
    limit = int(request.GET['limit'])
    data = Product.objects.order_by('-id')[offset:offset+limit]
    t = render_to_string('jtalks/more_products.html', {'data': data})
    return JsonResponse({'data': t})


def search_more_products(request):
    offset = int(request.GET['offset'])
    limit = int(request.GET['limit'])
    search = request.GET['search']
    search_data = Q(name__icontains=search)
    data = Product.objects.filter(search_data).order_by('id')[offset:offset+limit]
    t = render_to_string('jtalks/search_products.html', {'data': data})
    return JsonResponse({'data': t})

"""
def home(request):
    categories = Category.objects.all()
    courses_list = Courses.objects.all()
    paginator = Paginator(courses_list, 3)
    page = request.GET.get('page')
    courses = paginator.get_page(page)
    context = {
        'categories': categories,
        'courses': courses
    }
    return render(request, 'jtalks/home.html', context)

"""


def about(request):
    return render(request, 'jtalks/about.html')


class GetCourses(View):
    def get(self, request):
        get_courses = Courses.objects.filter(available=True)
        courses = []
        data = {}
        for i in range(len(get_courses)):
            x = get_courses[i].created
            datex = x.strftime("%d-%m-%Y")
            timex = x.strftime("%I:%M:%S %p")
            date_sent = datex + ' ' + 'at' + ' ' + timex
            cors = {
                'id': get_courses[i].id,
                #'categories': get_courses[i].categories.courses.all,
                'name': get_courses[i].name,
                'overview': get_courses[i].overview,
                'cover': get_courses[i].cover.url,
                'slug': get_courses[i].slug,
                'content_url': get_courses[i].content_url,
                'content_file': get_courses[i].content_file.url,
                'tutor': get_courses[i].tutor,
                'tutor_image': get_courses[i].tutor_image.url,
                'tutor_title': get_courses[i].tutor_title,
                'price': get_courses[i].price,
                'created': date_sent,
                'updated': get_courses[i].updated,
            }
            courses.append(cors)
        data['courses'] = courses
        return JsonResponse(data)


def search_products(request):
    query_product = request.POST.get('product')
    search_data = Q(name__icontains=query_product)
    search_results = Product.objects.filter(search_data).distinct()
    print(search_results)
    total_products = search_results.count()
    context = {
        'search_results': search_results,
        'query_product': query_product,
        'total_products': total_products
    }
    return render(request, 'jtalks/product_search.html', context)

jtalks/templates/jtalks/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Jtalks</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"/>

    <!-- custom css file link  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="{%static 'jtalks/style.css'%}" />
    <link rel="stylesheet" href="{%static 'jtalks/new_style.css'%}" />
    {% block blog_style %}
    {% endblock blog_style %}
  </head>

  <body>
    <nav>
      <img onclick="window.location.href='index.html'" src="#" alt="" />
      <!-- logo here -->
      <div class="navigation">
        <ul>
          <i id="menu-close" class="fas fa-times"></i>
          <li><a href="{% url 'jtalks:jtalks-home' %}" class="active">Home</a></li>
          <li><a href="about.html">About</a></li>
          <li><a href="{% url 'forum:post_list' %}">Blog</a></li>
          <li><a href="{% url 'forum:post_new' %}">{% block blog_new %}{% endblock blog_new %}</a></li>
          <li><a href="contact.html">Contact</a></li>
          <li>
            <div class="dropdown">
              <button class="dropbtn">Menu</button>
              <div class="dropdown-content">
                <a href="#">Courses (PDF)</a>
                <a href="#">Courses (Video)</a>
                <a href="#products_list">Products (hoodies and t-shirt)</a>
              </div>
            </div>
          </li>
          {% if request.user.is_authenticated %}
            <li>
              <div class="dropdown">
                <button class="dropbtn">Personal</button>
                <div class="dropdown-content">
                  <a href="{% url 'users:user_profile' request.user.id %}">Your Profile</a>
                  <a href="{% url 'courses:user_library' request.user.username %}">Your Library</a>
                </div>
              </div>
            </li>
            <li><a class="blue" href="{% url 'users:logout' %}">Logout</a></li>
          {% else %}
            <li><a class="blue" href="{% url 'users:login' %}">Login</a></li>
            <li><a class="blue" href="{% url 'users:signup' %}">Register</a></li>
          {% endif %}
          
        </ul>
        <img id="menu-btn" src="{%static 'jtalks/images/menu.png' %}" alt="" />
      </div>
    </nav>

    {%block content %} {%endblock content%}

    <!-- Footer starts here -->
    <footer>
      <div class="footer-col">
        <h3>Top Products</h3>
        <ul>
          <li>Manage Reputation</li>
        <li>Power Tools</li>
        <li>Managed Website</li>
        <li>Marketing Service</li>
        </ul>

      </div>
      <div class="footer-col">
        <h3>Quick Links</h3>
        <li>Jobs</li>
        <li>Brand Assets</li>
        <li>Investor Relations</li>
        <li>Terms of Service</li>
      </div>
      <div class="footer-col">
        <h3>Features</h3>
        <li>Manage Reputation</li>
        <li>Power Tools</li>
        <li>Managed Website</li>
        <li>Marketing Service</li>
      </div>
      <div class="footer-col">
        <h3>Resources</h3>
        <li>Guides</li>
        <li>Research</li>
        <li>Experts</li>
        <li>Marketing Service</li>
      </div>
      <div class="footer-col">
        <h3>Newsletter</h3>
        <p>You can trust us. we only send promo offers,</p>
        <div class="subscribe">
          <input type="text" name="" placeholder="Your Email Address" id="" />
          <a class="yellow" href="#">SUBSCRIBE</a>
        </div>
      </div>
      <div class="copyright">
        <p>
          Copyright ©2021 All rights reserved | This template is made by
          <a href="#">MoxTech</a>
        </p>
        <div class="pro-link">
          <i class="fab fa-facebook-f"></i>
          <i class="fab fa-instagram"></i>
          <i class="fab fa-linkedin-in"></i>
        </div>
      </div>
    </footer>
    <!-- footer end here -->
    <!-- jQuery js -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Boostrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"></script>
    {% block js %}
    {% endblock js %}
    <script>
      $("#menu-btn").click(function () {
        $("nav .navigation ul").addClass("active");
      });
      $("#menu-close").click(function () {
        $("nav .navigation ul").removeClass("active");
      });
    </script>

  </body>
</html>

jtalks/templates/jtalks/home.html
{% extends 'jtalks/base.html' %}
{% load static %}

<!-- home section starts  -->
{%block content %}
<section id="home">
  <h2>Impact Before Profit</h2>
  <p>
    We offer premimum course on Cryptocurrency, Social Media Marketing, Website
    Development and Personal Finance.
  </p>
  <div class="btn">
    <a class="blue" href="#">Learn More</a>
    <a class="yellow" href="#course">Visit Courses</a>
  </div>
</section>

<section id="features">
  <h1>Awesome Feature</h1>
  <p>Replenish man have thing gathering lights yielding shall you</p>
  <div class="fea-base">
    <div class="fea-box">
      <i class="fas fa-graduation-cap"></i>
      <h3>Scholarship Facility</h3>
      <p>One make creepeth, man bearing theira firmament won't great heaven</p>
    </div>

    <div class="fea-box">
      <i class="fas fa-file-certificate"></i>
      <h3>Sell Online Course</h3>
      <p>One make creepeth, man bearing theira firmament won't great heaven</p>
    </div>

    <div class="fea-box">
      <i class="fas fa-award"></i>
      <h3>Global Certification</h3>
      <p>One make creepeth, man bearing theira firmament won't great heaven</p>
    </div>
  </div>
</section>


<div>
  <div class="row">
    <div class="col-6">
      <h2>Featured Products here</h2>
      
    </div>
    
    <div class="col-6">
      <h2>Featured Courses here</h2>
      {% for course in courses %}
        {% if course.is_featured %}
          <div class="card product-box" style="width: 18rem;">
              <div>
                <img src="{{ course.content_file.url }}" class="card-img-top" alt="{{ course.name }}" height="200">
              </div>
              <div class="card-body">
                <h5 class="card-title">{{ course.name }}</h5>
                <h5>&#8358;{{ course.price }}</h5>
              </div>
              <div class="card-body">
                <button style="text-decoration: none; padding: 13px 45px; background: rgb(50, 50, 136); border: 1px solid #412e88; border-radius: 11px; color: white;">
                  <a href="/course/{{ course.id }}/{{ course.slug }}/">
                    Read More
                  </a>
                </button>
              </div>
            </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
</div>

<div>
  <div class="row">
    <div class="col-6">
    <section id="course">
      <h1>Courses Categories</h1>
      {% for category in categories %}
      <div class="category">
        <i class="fas fa-hand-point-right hand"></i> {{ category }} <br>
      </div>
      {% endfor %}
      
      <!--Start Products List Section -->
      <div class="products" id="products_list">
        <h1>Our Popular Products</h1>
        <form class="d-flex" method="POST" action="/search_products/">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search Products" name="product" required>
          <button class="btn btn-outline-success" type="submit" id="search_product">
            <i class="fas fa-search"></i>
          </button>
        </form>
        <div class="products-cards" style="display: flex; flex-direction: row">
          {% for product in products %}
            <div class="card card-box" style="width: 18rem;">
              <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}" height="200">
              <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <h5>&#8358;{{ product.price }}</h5>
              </div>
              <div class="card-body">
                <button style="text-decoration: none; padding: 13px 45px; background: rgb(50, 50, 136); border: 1px solid #412e88; border-radius: 11px; color: white;">
                  <a style="color: white;" href="{% url 'product:product_detail' product.id product.slug %}">
                    Read More
                  </a>
                </button>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
      <!--End Products List Section -->

      <div>
        <button style="text-decoration: none; padding: 13px 45px; background: rgb(50, 50, 136); border: 1px solid #412e88; border-radius: 11px; color: white;" id="load_more_products" data-total="{{ total_products }}" data-limit="3">
          Load More
          <i class="fas fa-angle-double-right load-more-icon"></i>
        </button>
        <p class="end-products" style="display: none;">No more products...</p>
      </div>
    </section>
    </div>
    
    <div class="col-6">
      <section id="course">
        <h1>Our Popular Courses</h1>
        <form class="d-flex" method="POST" action="/course/search_courses/">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search Courses" name="course" required>
          <button class="btn btn-outline-success" type="submit" id="search_course">
            <i class="fas fa-search"></i>
          </button>
        </form>
        <p>All our courses are available in both pdf and video formats</p>
        <div class="course-cards" style="display: flex; flex-direction: row">
          {% for course in courses %}
            <div class="card product-box" style="width: 18rem;">
              <div>
                <img src="{{ course.content_file.url }}" class="card-img-top" alt="{{ course.name }}" height="200">
              </div>
              <div class="card-body">
                <h5 class="card-title">{{ course.name }}</h5>
                <h5>&#8358;{{ course.price }}</h5>
              </div>
              <div class="card-body">
                <button style="text-decoration: none; padding: 13px 45px; background: rgb(50, 50, 136); border: 1px solid #412e88; border-radius: 11px; color: white;">
                  <a href="/course/{{ course.id }}/{{ course.slug }}/">
                    Read More
                  </a>
                </button>
              </div>
            </div>
          {% endfor %}
        </div>
        
        <div>
          <button style="text-decoration: none; padding: 13px 45px; background: rgb(50, 50, 136); border: 1px solid #412e88; border-radius: 11px; color: white;" id="load_more" data-total="{{ total_data }}" data-limit="3">
            Load More
            <i class="fas fa-angle-double-right load-more-icon"></i>
          </button>
          <p class="product_end" style="display: none;">No more courses...</p>
        </div>
      </section>
    </div>
  </div>
</div>

<section id="registration">
  <div class="reminder">
    <p>Get 100 Online Courses for Free</p>
    <h1>Register To Get It</h1>
    <div class="time">
      <div class="date">18<br />Days</div>
      <div class="date">23<br />Hours</div>
      <div class="date">06<br />Mins</div>
      <div class="date">58<br />Secs</div>
    </div>
  </div>
  <div class="form">
    {% if request.user.is_authenticated %}
    <h3>You are logged in as {{ request.user.username }}</h3>
    {% else %}
      <h3>Create Free Account NOW!</h3>
    <p class="text-center text-muted mt-5 mb-0">
      <a href="{% url 'users:signup' %}" class="fw-bold text-body">Sign Up</a>
    </p>
    
    <p class="text-center text-muted mt-5 mb-0">
      Already have an account?
      <a href="{% url 'users:login' %}" class="fw-bold text-body">Login here</a>
    </p>
    <div class="btn">
      <a class="yellow" href="#">Visit Courses</a>
    </div>
    {% endif %}  </div>
</section>

<section id="experts">
  <h1>Community Experts</h1>
  <p>Replenish man have thing gathering lights yielding shall you</p>
  <div class="expert-box">
    <div class="profile">
      <img src="{%static 'jtalks/images/pro1.webp' %}" alt="" />
      <h6>Ema Irnik</h6>
      <p>Python & Algorithm Expert</p>
      <div class="pro-link">
        <i class="fab fa-facebook-f"></i>
        <i class="fab fa-instagram"></i>
        <i class="fab fa-linkedin-in"></i>
      </div>
    </div>
    <div class="profile">
      <img src="{%static 'jtalks/images/pro2.webp' %}" alt="" />
      <h6>Jason</h6>
      <p>Data Analysis Expert</p>
      <div class="pro-link">
        <i class="fab fa-facebook-f"></i>
        <i class="fab fa-instagram"></i>
        <i class="fab fa-linkedin-in"></i>
      </div>
    </div>
    <div class="profile">
      <img src="{%static 'jtalks/images/pro3.webp' %}" alt="" />
      <h6>Maalik</h6>
      <p>Full Stack Developer</p>
      <div class="pro-link">
        <i class="fab fa-facebook-f"></i>
        <i class="fab fa-instagram"></i>
        <i class="fab fa-linkedin-in"></i>
      </div>
    </div>
    <div class="profile">
      <img src="{%static 'jtalks/images/pro4.webp' %}" alt="" />
      <h6>Jennifer</h6>
      <p>Design Expert</p>
      <div class="pro-link">
        <i class="fab fa-facebook-f"></i>
        <i class="fab fa-instagram"></i>
        <i class="fab fa-linkedin-in"></i>
      </div>
    </div>
  </div>
</section>
{%endblock content%}

{% block js %}
<script src="{% static 'jtalks/home.js' %}"></script>
{% endblock js %}

jtalks/templates/jtalks/more_courses.html
{% for course in data %}
  <div class="card product-box" style="width: 18rem;">
    <div>
      <img src="{{ course.content_file.url }}" class="card-img-top" alt="{{ course.name }}" height="200">
    </div>
    <div class="card-body">
      <h5 class="card-title">{{ course.name }}</h5>
      <h5>&#8358;{{ course.price }}</h5>
    </div>
    <div class="card-body">
      <button style="text-decoration: none; padding: 13px 45px; background: rgb(50, 50, 136); border: 1px solid #412e88; border-radius: 11px; color: white;">
        <a href="/course/{{ course.id }}/{{ course.slug }}/">
          Read More
        </a>
      </button>
    </div>
  </div>
{% endfor %}

jtalks/templates/jtalks/more_products.html
{% for product in data %}
  <div class="card card-box" style="width: 18rem;">
    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
    <div class="card-body">
      <h5 class="card-title">{{ product.name }}</h5>
      <h5>&#8358;{{ product.price }}</h5>
    </div>
    <div class="card-body">
      <button style="text-decoration: none; padding: 13px 45px; background: rgb(50, 50, 136); border: 1px solid #412e88; border-radius: 11px; color: white;">
        <a style="color: white;" href="{% url 'product:product_detail' product.id product.slug %}">
          Read More
        </a>
      </button>
    </div>
  </div>
{% endfor %}

jtalks/templates/jtalks/search_products.html
{% for product in data %}
  <div class="card card-box" style="width: 18rem;">
    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
    <div class="card-body">
      <h5 class="card-title">{{ product.name }}</h5>
      <h5>&#8358;{{ product.price }}</h5>
    </div>
    <div class="card-body">
      <button style="text-decoration: none; padding: 13px 45px; background: rgb(50, 50, 136); border: 1px solid #412e88; border-radius: 11px; color: white;">
        <a style="color: white;" href="{% url 'product:product_detail' product.id product.slug %}">
          Read More
        </a>
      </button>
    </div>
  </div>
{% endfor %}